{
  "formatVersion": "1.1",
  "component": {
    "group": "org.littletonrobotics.akit",
    "module": "akit-autolog",
    "version": "4.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "akit-autolog-4.1.1.jar",
          "url": "akit-autolog-4.1.1.jar",
          "size": 6186,
          "sha512": "a748396a761048fe5f65ad070b87ac8248e63377b69c58ab67d901732b1cf968272eb0f84f7b3d7f09b16f01f833a8a81d6dc4de6a991f627df1e2040881cd85",
          "sha256": "57c03ac41e9103b08c237025163b095ef1a4b3e5c272efa691435dfc8bf77b61",
          "sha1": "8bc9af5f0b6bee7e0bcfb2897b2193d3e4388db9",
          "md5": "ce315353539029bb5ede541fa8337db5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.squareup",
          "module": "javapoet",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "akit-autolog-4.1.1.jar",
          "url": "akit-autolog-4.1.1.jar",
          "size": 6186,
          "sha512": "a748396a761048fe5f65ad070b87ac8248e63377b69c58ab67d901732b1cf968272eb0f84f7b3d7f09b16f01f833a8a81d6dc4de6a991f627df1e2040881cd85",
          "sha256": "57c03ac41e9103b08c237025163b095ef1a4b3e5c272efa691435dfc8bf77b61",
          "sha1": "8bc9af5f0b6bee7e0bcfb2897b2193d3e4388db9",
          "md5": "ce315353539029bb5ede541fa8337db5"
        }
      ]
    }
  ]
}
